# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab543f69650f0be560ce41291b838baaeb19657ca6a906c2994aada0410884b93727eb37ecc13127e053f3b3cb662fbc1d8a5cf2d2d2255956bcff56620075b0

test:
  secret_key_base: cf4776bd1c32179b84a1e566b4211aa381cfe2c89d034008f0f11ca101a5ed3df6c93c2444a5983def238d5cb1b36b94ede612ce03ddd05ef53ed5fc145a5b73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
